---

- name: Ensure mongodb is started
  service: name={{ mongodb_daemon_name }} state=started enabled=yes
  changed_when: False

- name: Flush handlers to restart mongodb if necessary
  meta: flush_handlers

- name: Initial replica script
  template: src=initiate.js.j2 dest=/tmp/initiate.js
  tags: shell

- name: Run initiate script
  command: mongo {{ item }} /tmp/initiate.js
  tags: shell
  with_items: "{{mongodb_init_dbs}}"
  register: initiate

- debug: var=item.stdout_lines
  with_items: "{{ initiate.results }}"
  tags: shell
